import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ru'), Locale('uk')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'INDI CHARTS',

      // Settings
      'settings_title': 'Settings',
      'settings_notifications_title': 'Notifications',
      'settings_enable_notifications': 'Enable Notifications',
      'settings_enable_notifications_sub': 'Receive RSI alerts',
      'settings_sound': 'Sound',
      'settings_sound_sub': 'Sound notifications',
      'settings_vibration': 'Vibration',
      'settings_vibration_sub': 'Vibration on notifications',
      'settings_appearance_title': 'Appearance',
      'settings_theme': 'Theme',
      'settings_theme_dark': 'Dark',
      'settings_theme_light': 'Light',
      'settings_language': 'Language',
      'settings_language_russian': 'Russian',
      'settings_language_english': 'English',
      'settings_language_ukrainian': 'Ukrainian',
      'settings_data_title': 'Data',
      'settings_auto_refresh': 'Auto Refresh',
      'settings_auto_refresh_sub': 'Automatic data update',
      'settings_refresh_interval': 'Refresh Interval',
      'settings_refresh_interval_value': '{{seconds}} seconds',
      'settings_clear_cache': 'Clear Cache',
      'settings_clear_cache_sub': 'Delete saved data',
      'settings_widget_title': 'Widget Settings',
      'settings_widget_indicator': 'Widget Indicator',
      'settings_widget_indicator_select': 'Select Widget Indicator',
      'settings_account_title': 'Account',
      'settings_profile': 'Profile',
      'settings_profile_sub': 'Profile settings',
      'settings_sync': 'Sync',
      'settings_sync_sub': 'Sync between devices',
      'settings_about_title': 'About',
      'settings_version': 'Version',
      'settings_license': 'License',
      'settings_license_sub': 'Terms of use',
      'settings_support': 'Support',
      'settings_support_sub': 'Write to email',
      'settings_telegram_group': 'Telegram group',
      'settings_telegram_group_sub': 'Join our community',
      'settings_launch_email_error': 'Could not open email',
      'settings_launch_link_error': 'Could not open link',
      'settings_select_theme': 'Select Theme',
      'settings_select_language': 'Select Language',
      'settings_refresh_interval_title': 'Refresh Interval',
      'settings_refresh_interval_current':
          'Current interval: {{seconds}} seconds',
      'settings_cancel': 'Cancel',
      'settings_save': 'Save',
      'settings_clear_cache_title': 'Clear Cache',
      'settings_clear_cache_confirm':
          'Are you sure you want to delete all saved data?',
      'settings_clear_cache_success': 'Cache cleared',
      'settings_profile_dialog_title': 'Profile',
      'settings_profile_dialog_message':
          'Profile feature will be implemented in future versions',
      'settings_sync_dialog_title': 'Sync',
      'settings_sync_dialog_message':
          'Sync feature will be implemented in future versions',
      'settings_about_dialog_title': 'About',
      'settings_about_dialog_body':
          'RSI Widget App\nVersion: 1.0.0\n\nMobile application for RSI alerts and widgets\n© 2024 RSI Widget Team',
      'settings_license_dialog_title': 'License',
      'settings_license_dialog_message': '',
      'settings_support_dialog_title': 'Support',
      'settings_support_email': 'Email: ads.contact.manager@gmail.com',
      'settings_support_telegram': 'Telegram: @rsiwidget_support',
      'settings_support_github': 'GitHub: github.com/rsiwidget',
      'settings_ok': 'OK',
      'settings_widget_indicator_updated': 'Widget indicator updated',

      // Auth
      'auth_title': 'Welcome',
      'auth_subtitle': 'Sign in to sync your alerts across devices',
      'auth_sign_in_google': 'Sign in with Google',
      'auth_sign_out': 'Sign out',
      'auth_signing_in': 'Signing in...',
      'auth_error': 'Authentication error',
      'auth_error_message': 'Failed to sign in. Please try again.',
      'auth_skip': 'Continue without account',
      'auth_skip_message':
          'You can use the app without signing in, but your alerts won\'t sync across devices.',
      'auth_signed_in_as': 'Signed in as {{email}}',
      'auth_account': 'Account',
      'auth_sign_out_confirm': 'Are you sure you want to sign out?',
      'auth_sign_out_error': 'Error signing out: {{error}}',
      'common_user': 'User',

      // Common
      'common_cancel': 'Cancel',
      'common_save': 'Save',
      'common_delete': 'Delete',
      'common_ok': 'OK',
      'common_apply': 'Apply',
      'common_reset': 'Reset',
      'common_create': 'Create',
      'common_edit': 'Edit',
      'common_duplicate': 'Duplicate',
      'common_enable': 'Enable',
      'common_disable': 'Disable',
      'common_all': 'All',
      'common_yes': 'Yes',
      'common_no': 'No',
      'common_error': 'Error',
      'common_details': 'Details',
      'common_close': 'Close',
      'error_no_internet': 'No internet connection',
      'error_server_error': 'Server error. Please try again later',
      'error_timeout': 'Request timeout. Check your connection',
      'error_too_many_requests': 'Too many requests. Please wait a moment',
      'error_no_data': 'No data available',
      'error_unknown': 'An error occurred. Please try again',
      'error_symbol_not_found': 'Symbol "{{symbol}}" not found. Please enter a valid symbol',
      'error_symbol_validation_failed': 'Could not validate symbol "{{symbol}}. Please verify it exists',

      // Home
      'home_title': 'Overview',
      'home_watchlist_tooltip': 'Watchlist',
      'home_alerts_tooltip': 'Alerts',
      'home_settings_tooltip': 'Settings',
      'home_instrument_label': 'Instrument',
      'home_symbol_label': 'Symbol',
      'home_symbol_hint': 'Start typing symbol (e.g., AAPL)',
      'home_add_watchlist': 'Add to Watchlist',
      'home_timeframe_label': 'TF',
      'home_rsi_settings_title': 'RSI Settings',
      'home_rsi_period_label': 'RSI Period',
      'home_period_label': 'Period',
      'home_stoch_k_period_label': '%K Period',
      'home_stoch_d_period_label': '%D Period',
      'home_wpr_period_label': 'WPR Period',
      'home_lower_zone_label': 'Lower Zone',
      'home_upper_zone_label': 'Upper Zone',
      'home_wpr_lower_level_label': 'WPR Lower',
      'home_wpr_upper_level_label': 'WPR Upper',
      'home_stoch_lower_level_label': 'STOCH Lower',
      'home_stoch_upper_level_label': 'STOCH Upper',
      'home_reset_defaults_tooltip': 'Reset to default values',
      'home_apply_changes_tooltip': 'Apply changes',
      'home_current_indicator_title': '{{indicator}} ({{symbol}})',
      'home_rsi_chart_title': 'RSI Chart',
      'home_indicator_chart_title': '{{indicator}} Chart',
      'home_active_alerts_title': 'Active Alerts',
      'home_active_alerts_all': 'All',
      'home_no_active_alerts': 'No active alerts',
      'home_quick_actions_title': 'Quick Actions',
      'home_create_alert': 'Alert',
      'zone_below': 'Below',
      'zone_between': 'Between',
      'zone_above': 'Above',
      'home_refresh': 'Refresh',
      'home_watchlist_added': '{{symbol}} added to Watchlist',
      'home_watchlist_exists': '{{symbol}} already in Watchlist',
      'home_watchlist_limit_reached':
          'Watchlist limit reached (30 symbols). Remove a symbol to add a new one.',
      'home_no_data_for_timeframe':
          'No data for instrument on timeframe {{timeframe}}',
      'home_weekend_hint':
          'Markets are closed on weekends. For 4h and 1d timeframes, Yahoo Finance may not return fresh data.\nTry on business days (Monday-Friday).',
      'home_large_timeframe_hint':
          'For large timeframes, data for a longer period is required.',
      'home_check_symbol_hint': 'Check symbol spelling.',
      'home_insufficient_data':
          'Insufficient data for RSI calculation. Received {{count}} candles, minimum 15 required.',
      'home_instrument_not_found':
          'Instrument not found or no data available. Check symbol spelling.',
      'home_error_details_title': 'Error Details',
      'home_error_label_symbol': 'Symbol: {{symbol}}',
      'home_error_label_timeframe': 'Timeframe: {{timeframe}}',
      'home_error_label': 'Error:',
      'home_close': 'Close',
      'home_alpha_warning': 'ALPHA: some data can not be displayed',
      'search_no_results': 'No instruments found',

      // Markets
      'markets_title': 'Markets',
      'markets_crypto': 'Crypto',
      'markets_indexes': 'Indexes',
      'markets_forex': 'Forex',
      'markets_commodities': 'Commodities',
      'markets_stocks': 'Stocks',
      'markets_indicator_settings': 'Indicator Settings',

      // Alerts
      'alerts_title': 'Alerts',
      'alerts_filter_active': 'Active',
      'alerts_filter_inactive': 'Inactive',
      'alerts_stat_total': 'Total',
      'alerts_stat_active': 'Active',
      'alerts_stat_week': 'This Week',
      'alerts_empty_title': 'No alerts',
      'alerts_empty_subtitle': 'Create your first RSI alert',
      'alerts_levels_prefix': 'Levels: {{levels}}',
      'alerts_enabled': 'Alert enabled',
      'alerts_disabled': 'Alert disabled',
      'alerts_duplicate_success': 'Alert duplicated',
      'create_alert_duplicate_error':
          'Alert for {{symbol}} {{timeframe}} with the same settings already exists',
      'create_alert_limit_reached':
          'Alerts limit reached ({{max}} alerts). Remove an alert to add a new one.',
      'alerts_delete_title': 'Delete Alert',
      'alerts_delete_message':
          'Are you sure you want to delete alert for {{symbol}}?',
      'alerts_delete_success': 'Alert deleted',
      'alerts_error_loading': 'Error loading data: {{message}}',
      'alerts_error_generic': 'Error: {{message}}',
      'alerts_bulk_delete_confirm': 'Delete {{count}} alert(s)?',
      'alerts_bulk_processing': 'Processing {{count}} alert(s)...',
      'alerts_bulk_enabled': '{{count}} alert(s) enabled',
      'alerts_bulk_disabled': '{{count}} alert(s) disabled',
      'alerts_bulk_deleted': '{{count}} alert(s) deleted',

      // Create Alert
      'create_alert_title_new': 'Create Alert',
      'create_alert_title_edit': 'Edit Alert',
      'create_alert_basic_title': 'Basic Information',
      'create_alert_symbol_error': 'Select or enter symbol',
      'create_alert_description_label': 'Description (optional)',
      'create_alert_description_hint': 'Brief alert description',
      'create_alert_rsi_settings_title': 'RSI Settings',
      'create_alert_hysteresis_label': 'Hysteresis',
      'create_alert_levels_title': 'Levels',
      'create_alert_lower_level': 'Lower Level',
      'create_alert_upper_level': 'Upper Level',
      'create_alert_presets_3070': '30/70',
      'create_alert_presets_2080': '20/80',
      'create_alert_presets_2575': '25/75',
      'create_alert_presets_50': '50',
      'create_alert_at_least_one_level_required': 'At least one level must be enabled',
      'create_alert_invalid_lower_level': 'Lower level must be 1–99 (RSI/Stoch) or -99 to -1 (Williams %R)',
      'create_alert_invalid_upper_level': 'Upper level must be 1–99 (RSI/Stoch) or -99 to -1 (Williams %R)',
      'create_alert_invalid_levels_relationship': 'Lower level must be less than upper level',
      'create_alert_settings_title': 'Alert Settings',
      'create_alert_type_label': 'Alert Type',
      'create_alert_type_cross': 'Level Cross',
      'create_alert_type_enter': 'Enter Zone',
      'create_alert_type_exit': 'Exit Zone',
      'create_alert_cooldown_label': 'Cooldown (min)',
      'create_alert_repeatable': 'Repeatable',
      'create_alert_repeatable_sub': 'Alert can trigger multiple times',
      'create_alert_sound': 'Sound',
      'create_alert_sound_sub': 'Enable sound notification',
      'create_alert_on_close': 'Alert on candle close',
      'create_alert_on_close_sub': 'Waits for indicator value to stabilize, but reduces responsiveness',
      'create_alert_advanced_title': 'Advanced Settings',
      'create_alert_hysteresis_value': 'Hysteresis: {{value}}',
      'create_alert_cooldown_value': 'Cooldown: {{minutes}} min',
      'create_alert_cancel': 'Cancel',
      'create_alert_create': 'Create',
      'create_alert_save': 'Save',
      'create_alert_created': 'Alert created',
      'create_alert_updated': 'Alert updated',
      'create_alert_deleted': 'Alert deleted',
      'create_alert_delete_title': 'Delete Alert',
      'create_alert_delete_message':
          'Are you sure you want to delete this alert?',

      // Watchlist
      'watchlist_title': 'Watchlist',
      'watchlist_settings_title': 'Watchlist Settings',
      'watchlist_reset': 'Reset',
      'watchlist_apply': 'Apply',
      'watchlist_sort_desc': 'Sort by RSI (highest first)',
      'watchlist_sort_asc': 'Sort by RSI (lowest first)',
      'watchlist_empty_title': 'Watchlist is empty',
      'watchlist_empty_subtitle': 'Add instruments from the main screen',
      'watchlist_no_items': 'No items',
      'watchlist_remove_title': 'Remove from Watchlist?',
      'watchlist_remove_message': 'Remove {{symbol}} from watchlist?',
      'watchlist_remove': 'Remove',
      'watchlist_no_data': 'No data',
      'watchlist_rsi_prefix': 'RSI: {{value}}',
      'watchlist_error_loading': 'Error loading watchlist: {{message}}',

      // Chart
      'chart_no_data_for': 'No data for {{symbol}}',
      'chart_zone_oversold': 'Oversold',
      'chart_zone_neutral': 'Neutral',
      'chart_zone_overbought': 'Overbought',

      // Notifications
      'notification_watchlist_title': 'Watchlist: {{symbol}}',
      'notification_alert_title': '{{symbol}}',
      'notification_rsi_alert_body': 'RSI {{rsi}} crossed level {{level}} ({{type}})',
      'alert_above': 'above',
      'alert_below': 'below',
      'alert_between': 'between',
      
      // Alert messages
      'alert_message_cross_up': '{{indicator}} crossed level {{level}} upward ({{rsi}})',
      'alert_message_cross_down': '{{indicator}} crossed level {{level}} downward ({{rsi}})',
      'alert_message_enter_zone': '{{indicator}} entered zone {{lower}}-{{upper}}',
      'alert_message_exit_zone': '{{indicator}} exited zone {{lower}}-{{upper}}',
      
      // Watchlist mass alerts
      'watchlist_mass_alerts_title': 'Watchlist Alert',
      'watchlist_alert_anonymous_warning': 'Sign in to sync alerts across devices. Anonymous alerts will be lost if you reinstall the app.',
      'watchlist_creating_alerts': 'Creating alerts for {{count}} instrument(s)...',
      'watchlist_mass_alerts_empty': 'No Watchlist Alerts to delete',
      'watchlist_mass_alerts_error': 'Error deleting Watchlist Alerts',
      'watchlist_mass_alerts_delete_error': 'Error deleting Watchlist Alerts',
      'notification_connected_title': 'Connected to server',
      'notification_disconnected_title': 'Disconnected from server',
      'notification_receiving_data': 'Receiving RSI data',
      'notification_check_connection': 'Check internet connection',
      'notification_error_title': 'Application error',
      'notification_sync_success_title': 'Data synchronized',
      'notification_sync_error_title': 'Synchronization error',
      'notification_sync_success_body': 'RSI data for {{symbol}} updated',
      'notification_sync_error_body': 'Failed to update data for {{symbol}}',
      'notification_channel_rsi_alerts': 'RSI Alerts',
      'notification_channel_rsi_alerts_desc': 'Notifications about RSI level crossings',
      'notification_channel_general': 'General Notifications',
      'notification_channel_general_desc': 'General application notifications',
    },
    'ru': {
      'app_title': 'RSI Виджет',

      // Settings
      'settings_title': 'Настройки',
      'settings_notifications_title': 'Уведомления',
      'settings_enable_notifications': 'Включить уведомления',
      'settings_enable_notifications_sub': 'Получать RSI-алерты',
      'settings_sound': 'Звук',
      'settings_sound_sub': 'Звуковые уведомления',
      'settings_vibration': 'Вибрация',
      'settings_vibration_sub': 'Вибросигнал при уведомлениях',
      'settings_appearance_title': 'Оформление',
      'settings_theme': 'Тема',
      'settings_theme_dark': 'Тёмная',
      'settings_theme_light': 'Светлая',
      'settings_language': 'Язык',
      'settings_language_russian': 'Русский',
      'settings_language_english': 'Английский',
      'settings_language_ukrainian': 'Украинский',
      'settings_data_title': 'Данные',
      'settings_auto_refresh': 'Автообновление',
      'settings_auto_refresh_sub': 'Автоматическое обновление данных',
      'settings_refresh_interval': 'Интервал обновления',
      'settings_refresh_interval_value': '{{seconds}} секунд',
      'settings_clear_cache': 'Очистить кэш',
      'settings_clear_cache_sub': 'Удалить сохранённые данные',
      'settings_widget_title': 'Настройки виджета',
      'settings_widget_indicator': 'Индикатор виджета',
      'settings_widget_indicator_select': 'Выбрать индикатор виджета',
      'settings_account_title': 'Аккаунт',
      'settings_profile': 'Профиль',
      'settings_profile_sub': 'Настройки профиля',
      'settings_sync': 'Синхронизация',
      'settings_sync_sub': 'Синхронизация между устройствами',
      'settings_about_title': 'О приложении',
      'settings_version': 'Версия',
      'settings_license': 'Лицензия',
      'settings_license_sub': 'Условия использования',
      'settings_support': 'Поддержка',
      'settings_support_sub': 'Написать на email',
      'settings_telegram_group': 'Группа Telegram',
      'settings_telegram_group_sub': 'Присоединяйтесь к сообществу',
      'settings_launch_email_error': 'Не удалось открыть почту',
      'settings_launch_link_error': 'Не удалось открыть ссылку',
      'settings_select_theme': 'Выберите тему',
      'settings_select_language': 'Выберите язык',
      'settings_refresh_interval_title': 'Интервал обновления',
      'settings_refresh_interval_current':
          'Текущий интервал: {{seconds}} секунд',
      'settings_cancel': 'Отмена',
      'settings_save': 'Сохранить',
      'settings_clear_cache_title': 'Очистить кэш',
      'settings_clear_cache_confirm': 'Удалить все сохранённые данные?',
      'settings_clear_cache_success': 'Кэш очищен',
      'settings_profile_dialog_title': 'Профиль',
      'settings_profile_dialog_message':
          'Функция профиля будет добавлена в будущих версиях',
      'settings_sync_dialog_title': 'Синхронизация',
      'settings_sync_dialog_message':
          'Функция синхронизации будет добавлена в будущих версиях',
      'settings_about_dialog_title': 'О приложении',
      'settings_about_dialog_body':
          'RSI Widget App\nВерсия: 1.0.0\n\nМобильное приложение для RSI-алертов и виджетов\n© 2024 RSI Widget Team',
      'settings_license_dialog_title': 'Лицензия',
      'settings_license_dialog_message': '',
      'settings_support_dialog_title': 'Поддержка',
      'settings_support_email': 'Email: ads.contact.manager@gmail.com',
      'settings_support_telegram': 'Telegram: @rsiwidget_support',
      'settings_support_github': 'GitHub: github.com/rsiwidget',
      'settings_ok': 'OK',
      'settings_widget_indicator_updated': 'Индикатор виджета обновлён',

      // Auth
      'auth_title': 'Добро пожаловать',
      'auth_subtitle':
          'Войдите, чтобы синхронизировать алерты между устройствами',
      'auth_sign_in_google': 'Войти через Google',
      'auth_sign_out': 'Выйти',
      'auth_signing_in': 'Вход...',
      'auth_error': 'Ошибка входа',
      'auth_error_message': 'Не удалось войти. Попробуйте снова.',
      'auth_skip': 'Продолжить без аккаунта',
      'auth_skip_message':
          'Вы можете использовать приложение без входа, но алерты не будут синхронизироваться между устройствами.',
      'auth_signed_in_as': 'Вошли как {{email}}',
      'auth_account': 'Аккаунт',
      'auth_sign_out_confirm': 'Вы уверены, что хотите выйти?',
      'auth_sign_out_error': 'Ошибка при выходе: {{error}}',
      'common_user': 'Пользователь',

      // Common
      'common_cancel': 'Отмена',
      'common_save': 'Сохранить',
      'common_delete': 'Удалить',
      'common_ok': 'OK',
      'common_apply': 'Применить',
      'common_reset': 'Сбросить',
      'common_create': 'Создать',
      'common_edit': 'Редактировать',
      'common_duplicate': 'Дублировать',
      'common_enable': 'Включить',
      'common_disable': 'Выключить',
      'common_all': 'Все',
      'common_yes': 'Да',
      'common_no': 'Нет',
      'common_error': 'Ошибка',
      'common_details': 'Подробнее',
      'common_close': 'Закрыть',
      'error_no_internet': 'Нет соединения с интернетом',
      'error_server_error': 'Ошибка сервера. Попробуйте позже',
      'error_timeout': 'Превышено время ожидания. Проверьте соединение',
      'error_too_many_requests': 'Слишком много запросов. Подождите немного',
      'error_no_data': 'Нет данных для отображения',
      'error_unknown': 'Произошла ошибка. Попробуйте позже',
      'error_symbol_not_found': 'Тикер "{{symbol}}" не найден. Введите корректный тикер',
      'error_symbol_validation_failed': 'Не удалось проверить тикер "{{symbol}}". Убедитесь, что он существует',

      // Home
      'home_title': 'Обзор',
      'home_watchlist_tooltip': 'Список наблюдения',
      'home_alerts_tooltip': 'Алерты',
      'home_settings_tooltip': 'Настройки',
      'home_instrument_label': 'Инструмент',
      'home_symbol_label': 'Тикер',
      'home_symbol_hint': 'Начните вводить тикер (например, AAPL)',
      'home_add_watchlist': 'Добавить в список',
      'home_timeframe_label': 'ТФ',
      'home_rsi_settings_title': 'Настройки RSI',
      'home_rsi_period_label': 'Период RSI',
      'home_period_label': 'Период',
      'home_stoch_k_period_label': '%K Период',
      'home_stoch_d_period_label': '%D Период',
      'home_wpr_period_label': 'WPR Период',
      'home_lower_zone_label': 'Нижняя зона',
      'home_upper_zone_label': 'Верхняя зона',
      'home_wpr_lower_level_label': 'WPR Нижний',
      'home_wpr_upper_level_label': 'WPR Верхний',
      'home_stoch_lower_level_label': 'STOCH Нижний',
      'home_stoch_upper_level_label': 'STOCH Верхний',
      'home_reset_defaults_tooltip': 'Сбросить на значения по умолчанию',
      'home_apply_changes_tooltip': 'Применить изменения',
      'home_current_indicator_title': '{{indicator}} ({{symbol}})',
      'home_rsi_chart_title': 'График RSI',
      'home_indicator_chart_title': 'График {{indicator}}',
      'home_active_alerts_title': 'Активные алерты',
      'home_active_alerts_all': 'Все',
      'home_no_active_alerts': 'Нет активных алертов',
      'home_quick_actions_title': 'Быстрые действия',
      'home_create_alert': 'Алерт',
      'zone_below': 'Ниже',
      'zone_between': 'Между',
      'zone_above': 'Выше',
      'home_refresh': 'Обновить',
      'home_watchlist_added': '{{symbol}} добавлен в список наблюдения',
      'home_watchlist_exists': '{{symbol}} уже есть в списке наблюдения',
      'home_watchlist_limit_reached':
          'Достигнут лимит списка (30 символов). Удалите какой-нибудь символ чтобы добавить новый.',
      'home_no_data_for_timeframe':
          'Нет данных для инструмента на таймфрейме {{timeframe}}',
      'home_weekend_hint':
          'Рынки закрыты в выходные. Для таймфреймов 4h и 1d Yahoo Finance может не возвращать свежие данные.\nПопробуйте в будние дни (понедельник-пятница).',
      'home_large_timeframe_hint':
          'Для больших таймфреймов требуется более длительная история данных.',
      'home_check_symbol_hint': 'Проверьте написание тикера.',
      'home_insufficient_data':
          'Недостаточно данных для расчёта RSI. Получено {{count}} свечей, минимум требуется 15.',
      'home_instrument_not_found':
          'Инструмент не найден или нет данных. Проверьте написание тикера.',
      'home_error_details_title': 'Детали ошибки',
      'home_error_label_symbol': 'Символ: {{symbol}}',
      'home_error_label_timeframe': 'Таймфрейм: {{timeframe}}',
      'home_error_label': 'Ошибка:',
      'home_close': 'Закрыть',
      'home_alpha_warning': 'ALPHA: некоторые данные могут не отображаться',
      'search_no_results': 'Инструменты не найдены',

      // Markets
      'markets_title': 'Рынки',
      'markets_crypto': 'Крипто',
      'markets_indexes': 'Индексы',
      'markets_forex': 'Форекс',
      'markets_commodities': 'Сырьё',
      'markets_stocks': 'Акции',
      'markets_indicator_settings': 'Настройки индикатора',

      // Alerts
      'alerts_title': 'Уведомления',
      'alerts_filter_active': 'Активные',
      'alerts_filter_inactive': 'Неактивные',
      'alerts_stat_total': 'Всего',
      'alerts_stat_active': 'Активно',
      'alerts_stat_week': 'За неделю',
      'alerts_empty_title': 'Алертов нет',
      'alerts_empty_subtitle': 'Создайте первый RSI-алерт',
      'alerts_levels_prefix': 'Уровни: {{levels}}',
      'alerts_enabled': 'Алерт включён',
      'alerts_disabled': 'Алерт выключен',
      'alerts_duplicate_success': 'Алерт продублирован',
      'create_alert_duplicate_error':
          'Алерт для {{symbol}} {{timeframe}} с такими же настройками уже существует',
      'create_alert_limit_reached':
          'Достигнут лимит алертов ({{max}} алертов). Удалите алерт, чтобы добавить новый.',
      'alerts_delete_title': 'Удалить алерт',
      'alerts_delete_message': 'Удалить алерт для {{symbol}}?',
      'alerts_delete_success': 'Алерт удалён',
      'alerts_error_loading': 'Ошибка загрузки данных: {{message}}',
      'alerts_error_generic': 'Ошибка: {{message}}',
      'alerts_bulk_delete_confirm': 'Удалить {{count}} алерт(ов)?',
      'alerts_bulk_processing': 'Обработка {{count}} алерт(ов)...',
      'alerts_bulk_enabled': '{{count}} алерт(ов) включено',
      'alerts_bulk_disabled': '{{count}} алерт(ов) выключено',
      'alerts_bulk_deleted': '{{count}} алерт(ов) удалено',

      // Create Alert
      'create_alert_title_new': 'Создать алерт',
      'create_alert_title_edit': 'Редактировать алерт',
      'create_alert_basic_title': 'Основная информация',
      'create_alert_symbol_error': 'Выберите или введите тикер',
      'create_alert_description_label': 'Описание (необязательно)',
      'create_alert_description_hint': 'Краткое описание алерта',
      'create_alert_rsi_settings_title': 'Настройки RSI',
      'create_alert_hysteresis_label': 'Гистерезис',
      'create_alert_levels_title': 'Уровни',
      'create_alert_lower_level': 'Нижний уровень',
      'create_alert_upper_level': 'Верхний уровень',
      'create_alert_presets_3070': '30/70',
      'create_alert_presets_2080': '20/80',
      'create_alert_presets_2575': '25/75',
      'create_alert_presets_50': '50',
      'create_alert_at_least_one_level_required': 'Должен быть включен хотя бы один уровень',
      'create_alert_invalid_lower_level': 'Нижний уровень: 1–99 (RSI/Stoch) или -99…-1 (Williams %R)',
      'create_alert_invalid_upper_level': 'Верхний уровень: 1–99 (RSI/Stoch) или -99…-1 (Williams %R)',
      'create_alert_invalid_levels_relationship': 'Нижний уровень должен быть меньше верхнего',
      'create_alert_settings_title': 'Параметры алерта',
      'create_alert_type_label': 'Тип алерта',
      'create_alert_type_cross': 'Пересечение уровня',
      'create_alert_type_enter': 'Вход в зону',
      'create_alert_type_exit': 'Выход из зоны',
      'create_alert_cooldown_label': 'Пауза (мин)',
      'create_alert_repeatable': 'Повторяемый',
      'create_alert_repeatable_sub': 'Алерт может срабатывать несколько раз',
      'create_alert_sound': 'Звук',
      'create_alert_sound_sub': 'Включить звуковое уведомление',
      'create_alert_on_close': 'Алерт по закрытию свечи',
      'create_alert_on_close_sub': 'Ждет пока значение индикатора закрепится, но снижает отклик',
      'create_alert_advanced_title': 'Расширенные настройки',
      'create_alert_hysteresis_value': 'Гистерезис: {{value}}',
      'create_alert_cooldown_value': 'Пауза: {{minutes}} мин',
      'create_alert_cancel': 'Отмена',
      'create_alert_create': 'Создать',
      'create_alert_save': 'Сохранить',
      'create_alert_created': 'Алерт создан',
      'create_alert_updated': 'Алерт обновлён',
      'create_alert_deleted': 'Алерт удалён',
      'create_alert_delete_title': 'Удалить алерт',
      'create_alert_delete_message': 'Удалить этот алерт?',

      // Watchlist
      'watchlist_title': 'Список наблюдения',
      'watchlist_settings_title': 'Настройки списка',
      'watchlist_reset': 'Сбросить',
      'watchlist_apply': 'Применить',
      'watchlist_sort_desc': 'Сортировать по RSI (по убыванию)',
      'watchlist_sort_asc': 'Сортировать по RSI (по возрастанию)',
      'watchlist_empty_title': 'Список наблюдения пуст',
      'watchlist_empty_subtitle': 'Добавьте инструменты на главном экране',
      'watchlist_no_items': 'Нет элементов',
      'watchlist_remove_title': 'Удалить из списка?',
      'watchlist_remove_message': 'Удалить {{symbol}} из списка наблюдения?',
      'watchlist_remove': 'Удалить',
      'watchlist_no_data': 'Нет данных',
      'watchlist_rsi_prefix': 'RSI: {{value}}',
      'watchlist_error_loading': 'Ошибка загрузки списка: {{message}}',

      // Notifications
      'notification_watchlist_title': 'Watchlist: {{symbol}}',
      'notification_alert_title': '{{symbol}}',
      'notification_rsi_alert_body': 'RSI {{rsi}} пересек уровень {{level}} ({{type}})',
      'alert_above': 'выше',
      'alert_below': 'ниже',
      'alert_between': 'между',
      
      // Alert messages
      'alert_message_cross_up': '{{indicator}} пересек уровень {{level}} вверх ({{rsi}})',
      'alert_message_cross_down': '{{indicator}} пересек уровень {{level}} вниз ({{rsi}})',
      'alert_message_enter_zone': '{{indicator}} вошел в зону {{lower}}-{{upper}}',
      'alert_message_exit_zone': '{{indicator}} вышел из зоны {{lower}}-{{upper}}',
      
      // Watchlist mass alerts
      'watchlist_mass_alerts_title': 'Уведомления в списке',
      'watchlist_alert_anonymous_warning': 'Войдите в аккаунт для синхронизации алертов между устройствами. Анонимные алерты будут потеряны при переустановке приложения.',
      'watchlist_creating_alerts': 'Создание уведомлений для {{count}} инструмента(ов)...',
      'watchlist_mass_alerts_empty': 'Нет алертов списка наблюдения для удаления',
      'watchlist_mass_alerts_error': 'Ошибка удаления алертов списка наблюдения',
      'watchlist_mass_alerts_delete_error': 'Ошибка удаления алертов списка наблюдения',
      'notification_connected_title': 'Подключено к серверу',
      'notification_disconnected_title': 'Отключено от сервера',
      'notification_receiving_data': 'Получение данных RSI',
      'notification_check_connection': 'Проверьте интернет-соединение',
      'notification_error_title': 'Ошибка приложения',
      'notification_sync_success_title': 'Данные синхронизированы',
      'notification_sync_error_title': 'Ошибка синхронизации',
      'notification_sync_success_body': 'Данные RSI для {{symbol}} обновлены',
      'notification_sync_error_body': 'Не удалось обновить данные для {{symbol}}',
      'notification_channel_rsi_alerts': 'RSI Алерты',
      'notification_channel_rsi_alerts_desc': 'Уведомления о пересечениях уровней RSI',
      'notification_channel_general': 'Общие уведомления',
      'notification_channel_general_desc': 'Общие уведомления приложения',

      // Chart
      'chart_no_data_for': 'Нет данных для {{symbol}}',
      'chart_zone_oversold': 'Перепродано',
      'chart_zone_neutral': 'Нейтрально',
      'chart_zone_overbought': 'Перекуплено',
    },
    'uk': {
      'app_title': 'RSI Віджет',

      // Settings
      'settings_title': 'Налаштування',
      'settings_notifications_title': 'Сповіщення',
      'settings_enable_notifications': 'Увімкнути сповіщення',
      'settings_enable_notifications_sub': 'Отримувати RSI-алерти',
      'settings_sound': 'Звук',
      'settings_sound_sub': 'Звукові сповіщення',
      'settings_vibration': 'Вібрація',
      'settings_vibration_sub': 'Вібросигнал при сповіщеннях',
      'settings_appearance_title': 'Оформлення',
      'settings_theme': 'Тема',
      'settings_theme_dark': 'Темна',
      'settings_theme_light': 'Світла',
      'settings_language': 'Мова',
      'settings_language_russian': 'Російська',
      'settings_language_english': 'Англійська',
      'settings_language_ukrainian': 'Українська',
      'settings_data_title': 'Дані',
      'settings_auto_refresh': 'Автооновлення',
      'settings_auto_refresh_sub': 'Автоматичне оновлення даних',
      'settings_refresh_interval': 'Інтервал оновлення',
      'settings_refresh_interval_value': '{{seconds}} секунд',
      'settings_clear_cache': 'Очистити кеш',
      'settings_clear_cache_sub': 'Видалити збережені дані',
      'settings_widget_title': 'Налаштування віджета',
      'settings_widget_indicator': 'Індикатор віджета',
      'settings_widget_indicator_select': 'Вибрати індикатор віджета',
      'settings_account_title': 'Акаунт',
      'settings_profile': 'Профіль',
      'settings_profile_sub': 'Налаштування профілю',
      'settings_sync': 'Синхронізація',
      'settings_sync_sub': 'Синхронізація між пристроями',
      'settings_about_title': 'Про додаток',
      'settings_version': 'Версія',
      'settings_license': 'Ліцензія',
      'settings_license_sub': 'Умови використання',
      'settings_support': 'Підтримка',
      'settings_support_sub': 'Написати на email',
      'settings_telegram_group': 'Група Telegram',
      'settings_telegram_group_sub': 'Приєднуйтесь до спільноти',
      'settings_launch_email_error': 'Не вдалося відкрити пошту',
      'settings_launch_link_error': 'Не вдалося відкрити посилання',
      'settings_select_theme': 'Виберіть тему',
      'settings_select_language': 'Виберіть мову',
      'settings_refresh_interval_title': 'Інтервал оновлення',
      'settings_refresh_interval_current': 'Поточний інтервал: {{seconds}} секунд',
      'settings_cancel': 'Скасувати',
      'settings_save': 'Зберегти',
      'settings_clear_cache_title': 'Очистити кеш',
      'settings_clear_cache_confirm': 'Видалити всі збережені дані?',
      'settings_clear_cache_success': 'Кеш очищено',
      'settings_profile_dialog_title': 'Профіль',
      'settings_profile_dialog_message': 'Функція профілю буде додана в майбутніх версіях',
      'settings_sync_dialog_title': 'Синхронізація',
      'settings_sync_dialog_message': 'Функція синхронізації буде додана в майбутніх версіях',
      'settings_about_dialog_title': 'Про додаток',
      'settings_about_dialog_body': 'RSI Widget App\nВерсія: 1.0.0\n\nМобільний додаток для RSI-алертів і віджетів\n© 2024 RSI Widget Team',
      'settings_license_dialog_title': 'Ліцензія',
      'settings_license_dialog_message': '',
      'settings_support_dialog_title': 'Підтримка',
      'settings_support_email': 'Email: ads.contact.manager@gmail.com',
      'settings_support_telegram': 'Telegram: @rsiwidget_support',
      'settings_support_github': 'GitHub: github.com/rsiwidget',
      'settings_ok': 'OK',
      'settings_widget_indicator_updated': 'Індикатор віджета оновлено',

      // Auth
      'auth_title': 'Ласкаво просимо',
      'auth_subtitle': 'Увійдіть, щоб синхронізувати алерти між пристроями',
      'auth_sign_in_google': 'Увійти через Google',
      'auth_sign_out': 'Вийти',
      'auth_signing_in': 'Вхід...',
      'auth_error': 'Помилка входу',
      'auth_error_message': 'Не вдалося увійти. Спробуйте знову.',
      'auth_skip': 'Продовжити без акаунта',
      'auth_skip_message': 'Ви можете використовувати додаток без входу, але алерти не будуть синхронізуватися між пристроями.',
      'auth_signed_in_as': 'Увійшли як {{email}}',
      'auth_account': 'Акаунт',
      'auth_sign_out_confirm': 'Ви впевнені, що хочете вийти?',
      'auth_sign_out_error': 'Помилка при виході: {{error}}',
      'common_user': 'Користувач',

      // Common
      'common_cancel': 'Скасувати',
      'common_save': 'Зберегти',
      'common_delete': 'Видалити',
      'common_ok': 'OK',
      'common_apply': 'Застосувати',
      'common_reset': 'Скинути',
      'common_create': 'Створити',
      'common_edit': 'Редагувати',
      'common_duplicate': 'Дублювати',
      'common_enable': 'Увімкнути',
      'common_disable': 'Вимкнути',
      'common_all': 'Всі',
      'common_yes': 'Так',
      'common_no': 'Ні',
      'common_error': 'Помилка',
      'common_details': 'Деталі',
      'common_close': 'Закрити',
      'error_no_internet': 'Немає з\'єднання з інтернетом',
      'error_server_error': 'Помилка сервера. Спробуйте пізніше',
      'error_timeout': 'Перевищено час очікування. Перевірте з\'єднання',
      'error_too_many_requests': 'Занадто багато запитів. Зачекайте трохи',
      'error_no_data': 'Немає даних для відображення',
      'error_unknown': 'Сталася помилка. Спробуйте пізніше',
      'error_symbol_not_found': 'Тікер "{{symbol}}" не знайдено. Введіть коректний тікер',
      'error_symbol_validation_failed': 'Не вдалося перевірити тікер "{{symbol}}". Переконайтеся, що він існує',

      // Home
      'home_title': 'Огляд',
      'home_watchlist_tooltip': 'Список спостереження',
      'home_alerts_tooltip': 'Алерти',
      'home_settings_tooltip': 'Налаштування',
      'home_instrument_label': 'Інструмент',
      'home_symbol_label': 'Тікер',
      'home_symbol_hint': 'Почніть вводити тікер (наприклад, AAPL)',
      'home_add_watchlist': 'Додати до списку',
      'home_timeframe_label': 'ТФ',
      'home_rsi_settings_title': 'Налаштування RSI',
      'home_rsi_period_label': 'Період RSI',
      'home_period_label': 'Період',
      'home_stoch_k_period_label': '%K Період',
      'home_stoch_d_period_label': '%D Період',
      'home_wpr_period_label': 'WPR Період',
      'home_lower_zone_label': 'Нижня зона',
      'home_upper_zone_label': 'Верхня зона',
      'home_wpr_lower_level_label': 'WPR Нижній',
      'home_wpr_upper_level_label': 'WPR Верхній',
      'home_stoch_lower_level_label': 'STOCH Нижній',
      'home_stoch_upper_level_label': 'STOCH Верхній',
      'home_reset_defaults_tooltip': 'Скинути на значення за замовчуванням',
      'home_apply_changes_tooltip': 'Застосувати зміни',
      'home_current_indicator_title': '{{indicator}} ({{symbol}})',
      'home_rsi_chart_title': 'Графік RSI',
      'home_indicator_chart_title': 'Графік {{indicator}}',
      'home_active_alerts_title': 'Активні алерти',
      'home_active_alerts_all': 'Всі',
      'home_no_active_alerts': 'Немає активних алертів',
      'home_quick_actions_title': 'Швидкі дії',
      'home_create_alert': 'Алерт',
      'zone_below': 'Нижче',
      'zone_between': 'Між',
      'zone_above': 'Вище',
      'home_refresh': 'Оновити',
      'home_watchlist_added': '{{symbol}} додано до списку спостереження',
      'home_watchlist_exists': '{{symbol}} вже є в списку спостереження',
      'home_watchlist_limit_reached': 'Досягнуто ліміт списку (30 символів). Видаліть який-небудь символ щоб додати новий.',
      'home_no_data_for_timeframe': 'Немає даних для інструмента на таймфреймі {{timeframe}}',
      'home_weekend_hint': 'Ринки закриті в вихідні. Для таймфреймів 4h і 1d Yahoo Finance може не повертати свіжі дані.\nСпробуйте в робочі дні (понеділок-п\'ятниця).',
      'home_large_timeframe_hint': 'Для великих таймфреймів потрібна більш тривала історія даних.',
      'home_check_symbol_hint': 'Перевірте написання тікера.',
      'home_insufficient_data': 'Недостатньо даних для розрахунку RSI. Отримано {{count}} свічок, мінімум потрібно 15.',
      'home_instrument_not_found': 'Інструмент не знайдено або немає даних. Перевірте написання тікера.',
      'home_error_details_title': 'Деталі помилки',
      'home_error_label_symbol': 'Символ: {{symbol}}',
      'home_error_label_timeframe': 'Таймфрейм: {{timeframe}}',
      'home_error_label': 'Помилка:',
      'home_close': 'Закрити',
      'home_alpha_warning': 'ALPHA: деякі дані можуть не відображатися',
      'search_no_results': 'Інструменти не знайдено',

      // Markets
      'markets_title': 'Ринки',
      'markets_crypto': 'Крипто',
      'markets_indexes': 'Індекси',
      'markets_forex': 'Форекс',
      'markets_commodities': 'Сировина',
      'markets_stocks': 'Акції',
      'markets_indicator_settings': 'Налаштування індикатора',

      // Alerts
      'alerts_title': 'Сповіщення',
      'alerts_filter_active': 'Активні',
      'alerts_filter_inactive': 'Неактивні',
      'alerts_stat_total': 'Всього',
      'alerts_stat_active': 'Активно',
      'alerts_stat_week': 'За тиждень',
      'alerts_empty_title': 'Алертів немає',
      'alerts_empty_subtitle': 'Створіть перший RSI-алерт',
      'alerts_levels_prefix': 'Рівні: {{levels}}',
      'alerts_enabled': 'Алерт увімкнено',
      'alerts_disabled': 'Алерт вимкнено',
      'alerts_duplicate_success': 'Алерт продубльовано',
      'create_alert_duplicate_error': 'Алерт для {{symbol}} {{timeframe}} з такими ж налаштуваннями вже існує',
      'create_alert_limit_reached':
          'Досягнуто ліміт алертів ({{max}} алертів). Видаліть алерт, щоб додати новий.',
      'alerts_delete_title': 'Видалити алерт',
      'alerts_delete_message': 'Видалити алерт для {{symbol}}?',
      'alerts_delete_success': 'Алерт видалено',
      'alerts_error_loading': 'Помилка завантаження даних: {{message}}',
      'alerts_error_generic': 'Помилка: {{message}}',
      'alerts_bulk_delete_confirm': 'Видалити {{count}} алерт(ів)?',
      'alerts_bulk_processing': 'Обробка {{count}} алерт(ів)...',
      'alerts_bulk_enabled': '{{count}} алерт(ів) увімкнено',
      'alerts_bulk_disabled': '{{count}} алерт(ів) вимкнено',
      'alerts_bulk_deleted': '{{count}} алерт(ів) видалено',

      // Create Alert
      'create_alert_title_new': 'Створити алерт',
      'create_alert_title_edit': 'Редагувати алерт',
      'create_alert_basic_title': 'Основна інформація',
      'create_alert_symbol_error': 'Виберіть або введіть тікер',
      'create_alert_description_label': 'Опис (необов\'язково)',
      'create_alert_description_hint': 'Короткий опис алерта',
      'create_alert_rsi_settings_title': 'Налаштування RSI',
      'create_alert_hysteresis_label': 'Гістерезис',
      'create_alert_levels_title': 'Рівні',
      'create_alert_lower_level': 'Нижній рівень',
      'create_alert_upper_level': 'Верхній рівень',
      'create_alert_presets_3070': '30/70',
      'create_alert_presets_2080': '20/80',
      'create_alert_presets_2575': '25/75',
      'create_alert_presets_50': '50',
      'create_alert_at_least_one_level_required': 'Повинен бути увімкнений хоча б один рівень',
      'create_alert_invalid_lower_level': 'Нижній рівень: 1–99 (RSI/Stoch) або -99…-1 (Williams %R)',
      'create_alert_invalid_upper_level': 'Верхній рівень: 1–99 (RSI/Stoch) або -99…-1 (Williams %R)',
      'create_alert_invalid_levels_relationship': 'Нижній рівень має бути меншим за верхній',
      'create_alert_settings_title': 'Параметри алерта',
      'create_alert_type_label': 'Тип алерта',
      'create_alert_type_cross': 'Перетин рівня',
      'create_alert_type_enter': 'Вхід у зону',
      'create_alert_type_exit': 'Вихід із зони',
      'create_alert_cooldown_label': 'Пауза (мин)',
      'create_alert_repeatable': 'Повторюваний',
      'create_alert_repeatable_sub': 'Алерт може спрацьовувати кілька разів',
      'create_alert_sound': 'Звук',
      'create_alert_sound_sub': 'Увімкнути звукове сповіщення',
      'create_alert_on_close': 'Алерт по закриттю свічки',
      'create_alert_on_close_sub': 'Чекає, доки значення індикатора закріпиться, але знижує відгук',
      'create_alert_advanced_title': 'Розширені налаштування',
      'create_alert_hysteresis_value': 'Гістерезис: {{value}}',
      'create_alert_cooldown_value': 'Пауза: {{minutes}} мин',
      'create_alert_cancel': 'Скасувати',
      'create_alert_create': 'Створити',
      'create_alert_save': 'Зберегти',
      'create_alert_created': 'Алерт створено',
      'create_alert_updated': 'Алерт оновлено',
      'create_alert_deleted': 'Алерт видалено',
      'create_alert_delete_title': 'Видалити алерт',
      'create_alert_delete_message': 'Видалити цей алерт?',

      // Watchlist
      'watchlist_title': 'Список спостереження',
      'watchlist_settings_title': 'Налаштування списку',
      'watchlist_reset': 'Скинути',
      'watchlist_apply': 'Застосувати',
      'watchlist_sort_desc': 'Сортувати за RSI (за спаданням)',
      'watchlist_sort_asc': 'Сортувати за RSI (за зростанням)',
      'watchlist_empty_title': 'Список спостереження порожній',
      'watchlist_empty_subtitle': 'Додайте інструменти на головному екрані',
      'watchlist_no_items': 'Немає елементів',
      'watchlist_remove_title': 'Видалити зі списку?',
      'watchlist_remove_message': 'Видалити {{symbol}} зі списку спостереження?',
      'watchlist_remove': 'Видалити',
      'watchlist_no_data': 'Немає даних',
      'watchlist_rsi_prefix': 'RSI: {{value}}',
      'watchlist_error_loading': 'Помилка завантаження списку: {{message}}',

      // Chart
      'chart_no_data_for': 'Немає даних для {{symbol}}',
      'chart_zone_oversold': 'Перепродано',
      'chart_zone_neutral': 'Нейтрально',
      'chart_zone_overbought': 'Перекуплено',

      // Notifications
      'notification_watchlist_title': 'Watchlist: {{symbol}}',
      'notification_alert_title': '{{symbol}}',
      'notification_rsi_alert_body': 'RSI {{rsi}} перетнув рівень {{level}} ({{type}})',
      'alert_above': 'вище',
      'alert_below': 'нижче',
      'alert_between': 'між',
      
      // Alert messages
      'alert_message_cross_up': '{{indicator}} перетнув рівень {{level}} вгору ({{rsi}})',
      'alert_message_cross_down': '{{indicator}} перетнув рівень {{level}} вниз ({{rsi}})',
      'alert_message_enter_zone': '{{indicator}} увійшов у зону {{lower}}-{{upper}}',
      'alert_message_exit_zone': '{{indicator}} вийшов із зони {{lower}}-{{upper}}',
      
      // Watchlist mass alerts
      'watchlist_mass_alerts_title': 'Повідомлення у списку',
      'watchlist_alert_anonymous_warning': 'Увійдіть в акаунт для синхронізації алертів між пристроями. Анонімні алерти будуть втрачені при перевстановленні додатка.',
      'watchlist_creating_alerts': 'Створення сповіщень для {{count}} інструмента(ів)...',
      'watchlist_mass_alerts_empty': 'Немає алертів списку спостереження для видалення',
      'watchlist_mass_alerts_error': 'Помилка видалення алертів списку спостереження',
      'watchlist_mass_alerts_delete_error': 'Помилка видалення алертів списку спостереження',
      'notification_connected_title': 'Підключено до сервера',
      'notification_disconnected_title': 'Відключено від сервера',
      'notification_receiving_data': 'Отримання даних RSI',
      'notification_check_connection': 'Перевірте інтернет-з\'єднання',
      'notification_error_title': 'Помилка додатка',
      'notification_sync_success_title': 'Дані синхронізовано',
      'notification_sync_error_title': 'Помилка синхронізації',
      'notification_sync_success_body': 'Дані RSI для {{symbol}} оновлено',
      'notification_sync_error_body': 'Не вдалося оновити дані для {{symbol}}',
      'notification_channel_rsi_alerts': 'RSI Алерти',
      'notification_channel_rsi_alerts_desc': 'Сповіщення про перетини рівнів RSI',
      'notification_channel_general': 'Загальні сповіщення',
      'notification_channel_general_desc': 'Загальні сповіщення додатка',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key, {Map<String, String>? params}) {
    final languageCode = locale.languageCode;
    final values = _localizedValues[languageCode] ?? _localizedValues['en']!;
    final template = values[key] ?? _localizedValues['en']![key];
    if (template == null) return key;
    if (params == null || params.isEmpty) return template;

    return params.entries.fold<String>(
      template,
      (acc, entry) => acc.replaceAll('{{${entry.key}}}', entry.value),
    );
  }

  /// Get localized string by language code (for use without BuildContext)
  static Future<String> tByLanguage(
    String languageCode,
    String key, {
    Map<String, String>? params,
  }) async {
    final values = _localizedValues[languageCode] ?? _localizedValues['en']!;
    final template = values[key] ?? _localizedValues['en']![key];
    if (template == null) return key;
    if (params == null || params.isEmpty) return template;

    return params.entries.fold<String>(
      template,
      (acc, entry) => acc.replaceAll('{{${entry.key}}}', entry.value),
    );
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .map((e) => e.languageCode)
      .contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationExtension on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this);
}
